# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dochod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('date', models.DateField(default=datetime.date(2019, 1, 23))),
            ],
        ),
        migrations.CreateModel(
            name='DochodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='dochod',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DochodCategory'),
        ),
    ]
