# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190130_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wydatek',
            options={'ordering': ['-description', '-pk']},
        ),
        migrations.AlterField(
            model_name='dochod',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wydatek',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
