# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190130_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='running_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
